"""initial_migration

Revision ID: bb4c5e1b0925
Revises: 
Create Date: 2026-07-15 16:15:21.690947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4c5e1b0925'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('organizer', 'staff', 'guest', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_logged_in', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizer_id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('conference', 'concert', 'workshop', 'party', 'sports', 'networking', 'other', name='eventtype'), nullable=True),
    sa.Column('category', sa.Enum('music', 'tech', 'business', 'arts', 'food', 'sports', 'education', 'other', name='eventcategory'), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('virtual_link', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('access_type', sa.Enum('open', 'invite_only', 'ticketed', name='accesstype'), nullable=False),
    sa.Column('ticket_name', sa.String(length=100), nullable=True),
    sa.Column('ticket_price', sa.Float(), nullable=True),
    sa.Column('total_tickets', sa.Integer(), nullable=True),
    sa.Column('ticket_description', sa.Text(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'ongoing', 'completed', 'cancelled', name='eventstatus'), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', 'invite_only', name='eventvisibility'), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=True),
    sa.Column('check_ins', sa.Integer(), nullable=True),
    sa.Column('wizard_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_co_hosts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.Enum('view_only', 'check_in', 'manage_guests', 'full_access', name='cohostpermission'), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['organizers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('rsvp_status', sa.Enum('pending', 'confirmed', 'declined', 'waitlisted', 'checked_in', name='rsvpstatus'), nullable=False),
    sa.Column('rsvp_token', sa.String(), nullable=True),
    sa.Column('rsvp_responded_at', sa.DateTime(), nullable=True),
    sa.Column('plus_one_allowed', sa.Boolean(), nullable=True),
    sa.Column('plus_one_name', sa.String(length=200), nullable=True),
    sa.Column('plus_one_checked_in', sa.Boolean(), nullable=True),
    sa.Column('waitlist_position', sa.Integer(), nullable=True),
    sa.Column('invite_method', sa.Enum('email', 'sms', 'both', name='invitemethod'), nullable=True),
    sa.Column('invite_sent_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rsvp_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    op.drop_table('event_co_hosts')
    op.drop_table('otp_codes')
    op.drop_table('magic_link_tokens')
    op.drop_table('events')
    op.drop_table('organizers')
    # ### end Alembic commands ###
